kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: pod-watcher-sa
  namespace: pod-watcher
roleRef:
  kind: ClusterRole
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io