apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-watcher
  labels:
    app: pod-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-watcher
  template:
    metadata:
      labels:
        app: pod-watcher
    spec:
      serviceAccountName: pod-watcher-sa
      containers:
      - name: pod-watcher
        image: quay.io/chris_ricci/pod-watcher:v2